apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-ftdq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-ftdq
    app.kubernetes.io/part-of: that-python-app
  name: python-app-ftdq
  namespace: ralphjbean-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-app-ftdq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-app-ftdq
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c134d654085940fba9c4a5ea2eb4c5b2130762c7421128fe5428f9a6d9f4538c
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
