apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-ftdq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-ftdq
    app.kubernetes.io/part-of: that-python-app
  name: python-app-ftdq
  namespace: ralphjbean-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-app-ftdq
status:
  loadBalancer: {}
